---
title: "Materiais dos Encontros do MMLBH"
output: github_document
---

> Códigos e slides apresentados nos encontros do Meetup de Machine Learning de BH

## Meetup I

Realizado no dia 15 de dezembro de 2016.

[+ Material](https://github.com/mmlbh/Codes-and-presentations/tree/master/1%C2%BA%20MMLBh)

## Meetup II

Realizado no dia 19 de janeiro de 2017.

[+ Material](https://github.com/mmlbh/Codes-and-presentations/tree/master/2%C2%BA%20MMLBh)

## Meetup III

Realizado no dia 23 de fevereiro de 2017.

(Material Indisponível)

## Meetup IV

Realizado no dia 16 de março de 2017, na sede da [Nexer](https://www.nexer.com.br/).

### Atividades:

* Palestra "Como adivinhar pensamentos usando Feature Engineering e Machine Learning", com Sadraque Viana, CTO da [Nexer](https://www.nexer.com.br/).
    + [Slides]()
* Hands on "Análise de Dados na prática usando R", com [David Pinto](https://github.com/davpinto), CAO da [Nexer](https://www.nexer.com.br/).
    + [Apresentação](http://davpinto.com/mmlbh-eda/)
    + [Códigos](https://github.com/davpinto/mmlbh-eda)
    
## Meetup V

Realizado no dia 31 de março de 2017, na [Acelera MGTI](http://www.aceleramgti.com/).

### Atividades:

* Palestra "", com Thiago Akio, Software Engineer na [WorldSense](https://www.worldsense.com).
    + [Slides](https://docs.google.com/presentation/d/19yC6grfLLB3je3Kq3tYi30i9eA7Yzf38bD3N2x_WUUU/pub?slide=id.g35f391192_00)
* Hands on "Introdução ao Kaggle Datasets", com [David Pinto](https://github.com/davpinto), CAO da [Nexer](https://www.nexer.com.br/).
    + [Slides](https://davpinto.github.io/mmlbh-kaggle)
    + [Demo](https://github.com/davpinto/mmlbh-kaggle/blob/master/demo/kernel.md)
    + [Kaggle Kernel](https://www.kaggle.com/davidpinto/d/uciml/adult-census-income/validating-some-beliefs-about-income-bias/)
    + [Códigos](https://github.com/davpinto/mmlbh-kaggle)
    